### ISSUE TITLE
IDE: VS and CLion with cmake 

### ISSUE THREAD

**Issue by qPCR4vir** [JamesBremner/nana-amag#1]
Just not to forget: some day I will add:

In **VS**  simply drop nana.vcxproj from the nana repo into your solution: as in nana-demo:
https://github.com/qPCR4vir/nana-demo/blob/master/nana-demo-projects-vc2017/nana-demo-projects.sln#L262

And with cmake (CLion, VS) exactly the same: just add_subdirectory:
https://github.com/qPCR4vir/nana-demo/blob/master/CMakeLists.txt#L24

**Comment by JamesBremner** [comment]
Sorry,  I do not understand anything about your issue, probabaly because I am unfamiliar with VS and CLion.

Is there something you need me to do here?

**Comment by qPCR4vir** [comment]
> Is there something you need me to do here?

No. 
It is a reminder for me to add: 

>I welcome additional projects, please add them into a folder names build/your_favourite_ide.

Maybe somebodyelse can take my idea and add the project to your example.
VS uses a "sln - solution", and you can add "projects" to that. Very easy.

CLion (and now VS too) uses cmake as project builder. In cmake you can just use  `add_directory ` to add another "project", in this case the nana library.

**Comment by qPCR4vir** [comment]
If your users are used to VS, CLion or cmake, I think they will apreciate the provided links.

**Comment by JamesBremner** [comment]
Since there is no action for me, and the README already has a request for projects from other IDEs, I will close this issue.

I assume you have your own todo list for reminders like this.

> If your users are used to VS, CLion or cmake, I think they will apreciate the provided links.

My users use codeblocks.
